name: bot
on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: bot-run
        run: |
          npm i --no-package-lock --no-audit --no-fund
          npm start -- --only-new
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SYNC: 1
